{"uuid": "a8e839b7-cb00-4894-a7b2-02142ae3abe6", "children": ["9aa5aec9-df00-4406-9a54-1418e160032e"], "befores": [{"name": "_UnitTestCase__pytest_class_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"C:\\Program Files (x86)\\Python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Program Files (x86)\\Python\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Program Files (x86)\\Python\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Program Files (x86)\\Python\\lib\\site-packages\\_pytest\\unittest.py\", line 99, in fixture\n    setup()\n  File \"C:\\Users\\amal.mohamed.FLAIRSTECH\\PycharmProjects\\ScoutbeeAssignment\\OrangeHrmLiveWebSite\\Tests\\login_test.py\", line 19, in setUpClass\n    cls.driver = webdriver.Chrome(executable_path=\"../drivers/chromedriver.exe\")\n  File \"C:\\Program Files (x86)\\Python\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"C:\\Program Files (x86)\\Python\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 81, in start\n    raise WebDriverException(\n"}, "start": 1585458916896, "stop": 1585458916897}], "start": 1585458916896, "stop": 1585458917548}